# Generated by Django 2.2.4 on 2019-08-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=30, verbose_name='사이트명')),
                ('url', models.URLField(verbose_name='주소')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
            ],
            options={
                'ordering': ['site_name'],
            },
        ),
    ]
